---

- name: "Installation des paquets nécessaires"
  yum:
   name: "{{ item }}"
   state: present
  loop:
   "{{ paquets }}"
  
- name: "Changer le nom d'hôtes"
  hostname:
    name: "{{ hostname }}"

- name: "Attribuer les droits au dossier /var/www/html"
  file: 
    path: /var/www/html
    state: directory
    mode: '0755'

- name: "Copie des fichiers DB"
  copy:
    src: db-data/
    dest: /var/www/html/
    force: yes

- name: "Copie du template php"
  template:
    src: "template-php.j2"
    dest: /var/www/html/Database-Config.php

- name: "Copie du template html"
  template:
    src: "index.html.j2"
    dest: /var/www/html/index.html


- name: "Redémarrer httpd"
  systemd:
   name: httpd
   state: restarted
   enabled: yes