---


# - name: "Installation d'ansible"
#   apk:
#     name: "{{ item }}"
#     state: present
#   loop:
#     "{{ InstallPackages }}"


# - name: "Delete content & directory"
#   file:
#     state: absent
#     path: /root/.ssh/


# - name: "create directory"
#   file:
#     state: directory
#     path: /root/.ssh/
#     mode: '0755'
    


# - name: "generate SSH key"
#   openssh_keypair:
#     path: "~/.ssh/{{ssh_key_filename}}"
#     type: rsa
#     size: 4096
#     state: present
#     force: yes

- name: "hello"
  shell: 
    cmd: sshpass -p '"{{ item.key }}"' ssh-copy-id -o stricthostkeychecking=no {{ item.key }}@{{ item.key }}
  loop: "{{ password }}, {{ username }}, {{ ip }}"
