---

- name: "Installation d'ansible"
  apk:
    name: "{{ item }}"
    state: present
  loop:
    "{{ InstallPackages }}"


- name: "Delete content & directory"
  file:
    state: absent
    path: /root/.ssh/


- name: "create directory"
  file:
    state: directory
    path: /root/.ssh/
    mode: '0755'
    


- name: generate SSH key "{{ssh_key_filename}}"
  openssh_keypair:
    path: "~/.ssh/{{ssh_key_filename}}"
    type: rsa
    size: 4096
    state: present
    force: no



- name: "Command ssh copy-id"
  command: sshpass -p "{{ sshMdp }}" ssh-copy-id -o stricthostkeychecking=no {{ sshUser }}@{{ desHost }}
  loop:
   "{{ sshMdp[1], sshUser[1], desHost[1] }}"
