---


- name: "Installation des paquets"
  apk:
    name: "{{ item }}"
    state: present
  loop:
    "{{ InstallPackages }}"


- name: "Effacer le répertoire"
  file:
    state: absent
    path: /root/.ssh/


- name: "Création du répertoire"
  file:
    state: directory
    path: /root/.ssh/
    mode: '0755'
    


- name: "Génération de la clé ssh"
  openssh_keypair:
    path: "~/.ssh/{{ssh_key_filename}}"
    type: rsa
    size: 4096
    state: present
    force: yes

- name: "Connexion ssh"
  shell: 
    cmd: "{{ item }}"
  loop: 
    "{{ creds }}"

