---

- name: "Installation d'ansible"
  apk:
    name: "{{ item }}"
    state: present
  loop:
    "{{ InstallPackages }}"


- name: "Delete content & directory"
  file:
    state: absent
    path: /root/.ssh/


- name: "create directory"
  file:
    state: directory
    path: /root/.ssh/
    mode: '0755'
    


- name: generate SSH key "{{ssh_key_filename}}"
  openssh_keypair:
    path: "~/.ssh/{{ssh_key_filename}}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: "connecting"
  shell: 'sshpass -p "{{ item.0 }}" ssh-copy-id -o stricthostkeychecking=no {{ item.1 }}@{{ item.2 }}'
  loop:
    "{{ sshMdp|product(sshUser)|product(desHost)|list }}"
