---

- name: "Installation d'ansible"
  apk:
    name: "{{ item }}"
    state: present
  loop:
    "{{ InstallPackages }}"


- name: "Delete content & directory"
  file:
    state: absent
    path: /root/.ssh/


- name: "create directory"
  file:
    state: directory
    path: /root/.ssh/
    mode: '0755'
    


- name: "generate SSH key"
  openssh_keypair:
    path: "~/.ssh/{{ssh_key_filename}}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: "connecting"
  shell:
    cmd: sshpass -p "'{{ item }}'" ssh-copy-id -o stricthostkeychecking=no {{ item }}@192.168.59.150 
  loop:
    "{{ sshMdp|product(sshUser)|list }}"

    # "{{ sshMdp|product(sshUser)|product(desHost)|list }}"

