---





- name: "Remove file (delete file)"
  file:
    path: /etc/hosts
    state: absent
  become: yes

- name: "/etc/hosts template test"
  template: 
    src: etc_hosts.j2 
    dest: /etc/hosts
  become: yes


# - name: "copy test1 "
#    fetch:
#     src: /etc/resolv.conf
#     dest: ./resolv.conf
#     flat: true

# - name : "copy test2"
#    copy:
#     src: ./resolv.conf
#     dest: /etc/resolv.conf